name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/github-stats.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Generate English stats
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/stats.svg
        colors: dark-dimmed
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Generate English stats (light)
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/stats-light.svg
        colors: light
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Generate Armenian stats
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/hy/stats.svg
        colors: dark-dimmed
        locale: hy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Generate Armenian stats (light)
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/hy/stats-light.svg
        colors: light
        locale: hy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: push stats to the output branch
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
