name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/github-stats.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the contributions stats
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/stats.svg
        colors: dark-dimmed
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Generate the contributions stats
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/stats-light.svg
        colors: light
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Generate the contributions stats
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/hy/stats.svg
        colors: dark-dimmed
        locale: hy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Generate the contributions stats
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/hy/stats-light.svg
        colors: light
        locale: hy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
